version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - my_network
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: app_db
      DB_USERNAME: root
      DB_PASSWORD: root
      FFMPEG_BIN: /usr/bin/ffmpeg
      FFPROBE_BIN: /usr/bin/ffprobe
    command: ["sh", "-c", "wait-for-mysql.sh mysql && php artisan migrate --seed && apache2-foreground"]

  mysql:
    image: mariadb:10.8.3
    # Uncomment below when on Mac M1
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - my_network
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - my_network

networks:
  my_network:
    driver: bridge